source:
  # 文件或目录使用绝对路径，绝对路径按代码库根目录计算，以 / 开头。
  # 提供产品代码库中工具或框架自动生成的且在代码库中的代码，没有可为空。以便代码检查时进行排除处理。
  auto_generate_source:
    # 用于匹配文件; 匹配方式为正则表达式，例如[".*/java/test/.*", ".*/test.java"]
    filepath_regex: [".*/inner/.*", ".*/inner.py"]
