spring.application.name=spring-boot-starter

server.address=0.0.0.0
server.port=8080

# 配置 starter 时，优先级：环境变量 > 配置文件，更多配置请参考：https://opentelemetry.io/docs/languages/java/configuration/

# 服务名，一个应用可以有多个服务，通过该属性区分。有关服务名配置的更多信息，请参考：https://opentelemetry.io/docs/languages/sdk-configuration/general/#otel_service_name
# 以下配置会被环境变量 `OTEL_SERVICE_NAME=xxx` 或 `OTEL_RESOURCE_ATTRIBUTES="service.name=xxx"` 覆盖
otel.service.name=java-spring-boot-starter

# Exporter 导出数据时附加额外的 Headers，多个 key-value 以逗号分隔，更多信息请参考：https://opentelemetry.io/docs/languages/sdk-configuration/otlp-exporter/#otel_exporter_otlp_headers
# 【非常重要】`x-bk-token` 是蓝鲸 APM 在接收端的凭证，请传入应用真实 Token，否则数据无法正常上报到 APM。
# 以下配置会被环境变量 `OTEL_EXPORTER_OTLP_HEADERS="x-bk-token=xxx"` 覆盖
otel.exporter.otlp.headers=x-bk-token=todo

# Resource 代表观测数据所属的资源实体，并通过资源属性进行描述。更多信息请参考：https://opentelemetry.io/docs/concepts/resources/
# # Resource Attributes 设置，多个 key-value 以逗号分隔，例如：`key1=value1,key2=value2`。更多信息请参考：https://opentelemetry.io/docs/languages/sdk-configuration/general/#otel_resource_attributes
# 以下配置会被环境变量 OTEL_RESOURCE_ATTRIBUTES="xxx=2,yyy=1" 覆盖
otel.resource.attributes=xxx=1,yyy=2

# 指定上报协议。上报协议改变时，上报地址也需要手动修改，更多信息请参考：https://opentelemetry.io/docs/languages/sdk-configuration/otlp-exporter/#protocol-configuration
# 【默认/推荐】protobuf/http：使用 HTTP 协议上报
# 【可选】grpc：使用 gRPC 上报，如果使用该方式，请确保 `otel.exporter.otlp.endpoint` 也同步改为 gRPC 上报地址
# 以下配置会被环境变量 `OTEL_EXPORTER_OTLP_PROTOCOL="xxx"` 覆盖
otel.exporter.otlp.protocol=http/protobuf

# 指定上报地址。如果使用 gRPC 上报，上报地址的端口号应改为 4317，即 http://host.docker.internal:4317
# 更多信息请参考：https://opentelemetry.io/docs/languages/sdk-configuration/otlp-exporter/#otel_exporter_otlp_endpoint
# 以下配置会被环境变量 `OTEL_EXPORTER_OTLP_ENDPOINT=xxx` 覆盖
otel.exporter.otlp.endpoint=http://localhost:4318